import {
  catalogPath,
  catalogDeltaPath,
  catalogSyncPath,
  collectionDetailPath,
  contentDetailPath,
  analyticsDashboardPath,
  analyticsEventsPath,
  adminReviewAuditPath,
  adminReviewDetailPath,
  adminReviewQueuePath,
  creatorDraftDetailPath,
  creatorDraftsPath,
  creatorDraftSyncQueuePath,
  creatorDetailPath,
  creatorProcessingJobDetailPath,
  creatorProcessingJobsPath,
  creatorUploadAssetsPath,
  creatorUploadDetailPath,
  creatorUploadSessionsPath,
  discoveryQueryPath,
  aiDiscoveryHomePath,
  aiDiscoveryMoodPath,
  aiDiscoverySearchPath,
  socialWatchFriendsPath,
  socialWatchInviteDetailPath,
  socialWatchPartiesPath,
  socialWatchPartyDetailPath,
  socialWatchSharedLibraryPath,
  socialWatchSummaryPath,
  creatorEconomyDashboardPath,
  creatorEconomyMembershipsPath,
  creatorEconomyPaidCollectionsPath,
  creatorEconomyPaidPremieresPath,
  creatorEconomyPayoutsPath,
  creatorEconomyRevenueSharesPath,
  creatorEconomyTipsPath,
  creatorAssistantMetadataPath,
  creatorAssistantPosterPath,
  creatorAssistantPublishingPath,
  creatorAssistantRightsPath,
  creatorAssistantSEOPath,
  creatorAssistantSummaryPath,
  creatorAssistantTrailerPath,
  identityDataExportPath,
  identityDeleteRequestPath,
  identityAppleExchangePath,
  identityAuditPath,
  identityDevSignInPath,
  identityMePath,
  identityRefreshPath,
  identitySignOutPath,
  notificationDeliveryAuditPath,
  notificationDevicesPath,
  notificationInboxPath,
  notificationPreferencesPath,
  notificationTestPushPath,
  monetizationAuditPath,
  monetizationEntitlementsPath,
  monetizationProductsPath,
  monetizationRestorePath,
  monetizationRevokePath,
  monetizationTransactionsPath,
  openAPIPath,
  platformOperationsAuditPath,
  platformOperationsModerationDetailPath,
  platformOperationsModerationFlagsPath,
  platformOperationsModerationPath,
  platformOperationsRightsDetailPath,
  platformOperationsRightsPath,
  platformOperationsSummaryPath,
  betaAuditPath,
  betaCrashDetailPath,
  betaCrashReportsPath,
  betaEnrollPath,
  betaFeedbackDetailPath,
  betaFeedbackPath,
  betaProgramPath,
  betaStabilityPath,
  publicReleaseAuditPath,
  publicReleaseCreatorOnboardingPath,
  publicReleaseCutoverPath,
  publicReleaseHotfixDetailPath,
  publicReleaseHotfixPath,
  publicReleaseMonitorPath,
  publicReleaseSubmitPath,
  publicReleaseSummaryPath,
  playbackDescriptorPath,
  playbackHLSPath,
  readinessPath,
  securityRateLimitProbePath,
  viewerLibraryOfflinePath,
  viewerLibraryPath,
  viewerLibraryProgressPath,
  viewerLibrarySavePath
} from "../contracts.js";

export function openAPISpec(): Record<string, unknown> {
  return {
    openapi: "3.1.0",
    info: {
      title: "HighFive Cinema Production Backend Foundation",
      version: "0.29.0",
      description: "Read-only local catalog foundation for P29A. Authentication, uploads, payments, and media processing are out of scope."
    },
    paths: {
      "/health": { get: { summary: "Health check" } },
      [readinessPath]: { get: { summary: "Readiness check" } },
      [catalogPath]: { get: { summary: "Fetch read-only catalog" } },
      [catalogSyncPath]: { get: { summary: "Fetch full catalog sync snapshot" } },
      [catalogDeltaPath]: { get: { summary: "Fetch catalog delta sync payload" } },
      [`${contentDetailPath}{id}`]: { get: { summary: "Fetch content detail" } },
      [`${creatorDetailPath}{id}`]: { get: { summary: "Fetch creator detail" } },
      [`${collectionDetailPath}{id}`]: { get: { summary: "Fetch collection detail" } },
      [creatorDraftsPath]: {
        get: { summary: "List authenticated creator drafts" },
        post: { summary: "Create authenticated creator draft" }
      },
      [`${creatorDraftDetailPath}{id}`]: {
        get: { summary: "Fetch authenticated creator draft" },
        patch: { summary: "Update authenticated creator draft with optimistic concurrency" }
      },
      [`${creatorDraftDetailPath}{id}/archive`]: { post: { summary: "Archive authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/restore`]: { post: { summary: "Restore authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/submit`]: { post: { summary: "Submit creator project for admin review" } },
      [`${creatorDraftDetailPath}{id}/withdraw`]: { post: { summary: "Withdraw creator project from admin review" } },
      [`${creatorDraftDetailPath}{id}/revisions`]: { get: { summary: "Fetch creator draft revision history" } },
      [creatorDraftSyncQueuePath]: { get: { summary: "Fetch creator draft sync queue audit records" } },
      [adminReviewQueuePath]: { get: { summary: "Fetch admin publishing review queue" } },
      [`${adminReviewDetailPath}{id}/request-revision`]: { post: { summary: "Request creator revisions for a reviewed project" } },
      [`${adminReviewDetailPath}{id}/approve`]: { post: { summary: "Approve reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/reject`]: { post: { summary: "Reject reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/schedule`]: { post: { summary: "Schedule approved creator project" } },
      [`${adminReviewDetailPath}{id}/publish`]: { post: { summary: "Publish approved creator project into public catalog" } },
      [`${adminReviewDetailPath}{id}/unpublish`]: { post: { summary: "Remove published creator project from public catalog" } },
      [`${adminReviewDetailPath}{id}/archive`]: { post: { summary: "Archive reviewed creator project" } },
      [adminReviewAuditPath]: { get: { summary: "Fetch admin publishing audit trail" } },
      [creatorUploadSessionsPath]: { post: { summary: "Create short-lived creator upload session" } },
      [`${creatorUploadDetailPath}{id}/blob`]: { put: { summary: "Upload verified asset bytes into local object storage" } },
      [`${creatorUploadDetailPath}{id}/cancel`]: { post: { summary: "Cancel creator upload session and cleanup local staging object" } },
      [creatorUploadAssetsPath]: { get: { summary: "List uploaded creator asset records" } },
      [creatorProcessingJobsPath]: {
        get: { summary: "List creator media processing jobs" },
        post: { summary: "Create local media processing job for uploaded asset" }
      },
      [`${creatorProcessingJobDetailPath}{id}/retry`]: { post: { summary: "Retry a failed or completed media processing job idempotently" } },
      [playbackDescriptorPath]: { post: { summary: "Resolve a short-lived playback descriptor for entitled content" } },
      [`${playbackHLSPath}{id}/master.m3u8`]: { get: { summary: "Fetch signed local HLS master manifest for a processed asset" } },
      [viewerLibraryPath]: { get: { summary: "Fetch authenticated viewer library, progress, and offline state" } },
      [viewerLibrarySavePath]: { post: { summary: "Save or remove authenticated viewer library title state" } },
      [viewerLibraryProgressPath]: { post: { summary: "Persist authenticated viewer playback progress" } },
      [viewerLibraryOfflinePath]: { post: { summary: "Persist authenticated viewer offline download state" } },
      [discoveryQueryPath]: { get: { summary: "Search, filter, paginate, and recommend catalog content" } },
      [aiDiscoveryHomePath]: { get: { summary: "Fetch personalized V2 home recommendations, taste profile, mood rails, and continue-watching intelligence" } },
      [aiDiscoverySearchPath]: { get: { summary: "Fetch V2 taste-aware ranked search results with matched-field explanations" } },
      [aiDiscoveryMoodPath]: { get: { summary: "Fetch V2 mood-based discovery recommendations" } },
      [socialWatchSummaryPath]: { get: { summary: "Fetch authenticated Social Watch parties, invites, comments, reactions, friends, and voice-room state" } },
      [socialWatchFriendsPath]: { post: { summary: "Create or fetch an authenticated friend relationship for Social Watch" } },
      [socialWatchSharedLibraryPath]: { post: { summary: "Share an authenticated local library selection with another user" } },
      [socialWatchPartiesPath]: { post: { summary: "Create an authenticated watch party for catalog content" } },
      [`${socialWatchPartyDetailPath}{id}/invite`]: { post: { summary: "Invite a user to an existing watch party" } },
      [`${socialWatchPartyDetailPath}{id}/playback`]: { post: { summary: "Synchronize watch-party playback position and state" } },
      [`${socialWatchPartyDetailPath}{id}/reactions`]: { post: { summary: "Record a watch-party reaction at a playback position" } },
      [`${socialWatchPartyDetailPath}{id}/comments`]: { post: { summary: "Record a watch-party comment at a playback position" } },
      [`${socialWatchPartyDetailPath}{id}/voice-room`]: { post: { summary: "Update local voice-room state for a watch party" } },
      [`${socialWatchInviteDetailPath}{id}/respond`]: { post: { summary: "Accept or decline an authenticated watch-party invite" } },
      [creatorEconomyDashboardPath]: { get: { summary: "Fetch creator economy dashboard with revenue, memberships, packages, and payout preview" } },
      [creatorEconomyPayoutsPath]: {
        get: { summary: "Fetch creator payout previews and available creator net revenue" },
        post: { summary: "Queue a creator payout preview without external transfer" }
      },
      [creatorEconomyRevenueSharesPath]: { post: { summary: "Update creator revenue share rules for owned content" } },
      [creatorEconomyTipsPath]: { post: { summary: "Record a viewer tip into the creator economy ledger" } },
      [creatorEconomyMembershipsPath]: { post: { summary: "Activate a viewer creator-membership ledger record" } },
      [creatorEconomyPaidCollectionsPath]: { post: { summary: "Create a creator paid collection package" } },
      [creatorEconomyPaidPremieresPath]: { post: { summary: "Create a creator paid premiere package" } },
      [creatorAssistantSummaryPath]: {
        get: { summary: "Fetch local creator assistant suggestions for the authenticated workspace" },
        post: { summary: "Fetch local creator assistant suggestions for an explicit project context" }
      },
      [creatorAssistantMetadataPath]: { post: { summary: "Generate local metadata suggestions for a creator project" } },
      [creatorAssistantPosterPath]: { post: { summary: "Generate local poster direction suggestions for a creator project" } },
      [creatorAssistantTrailerPath]: { post: { summary: "Generate local trailer structure suggestions for a creator project" } },
      [creatorAssistantPublishingPath]: { post: { summary: "Generate local publishing readiness suggestions for a creator project" } },
      [creatorAssistantSEOPath]: { post: { summary: "Generate local search and SEO suggestions for a creator project" } },
      [creatorAssistantRightsPath]: { post: { summary: "Generate local rights readiness suggestions for a creator project" } },
      [analyticsEventsPath]: { post: { summary: "Ingest versioned analytics event batches with idempotency and privacy controls" } },
      [analyticsDashboardPath]: { get: { summary: "Fetch aggregate analytics for creator and platform dashboards" } },
      [notificationDevicesPath]: { post: { summary: "Register an APNs device token suffix for the authenticated user" } },
      [notificationPreferencesPath]: {
        get: { summary: "Fetch authenticated notification preferences" },
        patch: { summary: "Update authenticated notification preferences" }
      },
      [notificationInboxPath]: { get: { summary: "Fetch authenticated in-app notification inbox" } },
      [notificationTestPushPath]: { post: { summary: "Queue a development notification and delivery audit record" } },
      [notificationDeliveryAuditPath]: { get: { summary: "Fetch notification delivery audit records" } },
      [monetizationProductsPath]: { get: { summary: "Fetch StoreKit 2 product catalog and entitlement scopes" } },
      [monetizationEntitlementsPath]: { get: { summary: "Fetch authenticated backend entitlement records" } },
      [monetizationTransactionsPath]: { post: { summary: "Record verified StoreKit 2 transaction state" } },
      [monetizationRestorePath]: { post: { summary: "Restore authenticated active entitlement records" } },
      [monetizationRevokePath]: { post: { summary: "Revoke authenticated product entitlement" } },
      [monetizationAuditPath]: { get: { summary: "Fetch authenticated monetization audit events" } },
      [platformOperationsSummaryPath]: { get: { summary: "Fetch admin rights, moderation, availability, and health summary" } },
      [platformOperationsRightsPath]: { get: { summary: "Fetch admin rights windows and territory availability" } },
      [`${platformOperationsRightsDetailPath}{id}/expire`]: { post: { summary: "Expire rights window and remove catalog availability" } },
      [`${platformOperationsRightsDetailPath}{id}/restore`]: { post: { summary: "Restore rights window and catalog availability" } },
      [platformOperationsModerationPath]: { get: { summary: "Fetch admin moderation queue" } },
      [platformOperationsModerationFlagsPath]: { post: { summary: "Flag content for moderation review" } },
      [`${platformOperationsModerationDetailPath}{id}/clear`]: { post: { summary: "Clear moderation case" } },
      [`${platformOperationsModerationDetailPath}{id}/needs-revision`]: { post: { summary: "Request moderation revision" } },
      [`${platformOperationsModerationDetailPath}{id}/takedown`]: { post: { summary: "Apply moderation takedown and remove catalog availability" } },
      [`${platformOperationsModerationDetailPath}{id}/restore`]: { post: { summary: "Restore content from moderation takedown" } },
      [platformOperationsAuditPath]: { get: { summary: "Fetch platform operations audit trail" } },
      [betaProgramPath]: { get: { summary: "Fetch admin beta program status, cohorts, stability, and open issues" } },
      [betaEnrollPath]: { post: { summary: "Enroll an authenticated account into an allowed beta cohort" } },
      [betaFeedbackPath]: { post: { summary: "Submit beta feedback for an enrolled tester" } },
      [`${betaFeedbackDetailPath}{id}/resolve`]: { post: { summary: "Resolve or triage beta feedback as an admin" } },
      [betaCrashReportsPath]: { post: { summary: "Submit a beta crash report for an enrolled tester" } },
      [`${betaCrashDetailPath}{id}/resolve`]: { post: { summary: "Resolve a beta crash report as an admin" } },
      [betaStabilityPath]: { get: { summary: "Fetch beta stability summary for launch readiness" } },
      [betaAuditPath]: { get: { summary: "Fetch beta operations audit trail" } },
      [publicReleaseSummaryPath]: { get: { summary: "Fetch public release state, monitoring, launch analytics, hotfixes, and onboarding" } },
      [publicReleaseSubmitPath]: { post: { summary: "Record public release submission state and manual external submission confirmation" } },
      [publicReleaseCutoverPath]: { post: { summary: "Record public release cutover after manual public release confirmation" } },
      [publicReleaseMonitorPath]: { get: { summary: "Fetch public release monitoring and launch analytics snapshot" } },
      [publicReleaseHotfixPath]: { post: { summary: "Open a public release hotfix tracking record" } },
      [`${publicReleaseHotfixDetailPath}{id}/update`]: { post: { summary: "Update public release hotfix state" } },
      [publicReleaseCreatorOnboardingPath]: { post: { summary: "Record launch creator onboarding state" } },
      [publicReleaseAuditPath]: { get: { summary: "Fetch public release audit trail" } },
      [identityMePath]: { get: { summary: "Fetch authenticated session and permission summary" } },
      [identityDevSignInPath]: { post: { summary: "Create a simulator development identity session" } },
      [identityAppleExchangePath]: { post: { summary: "Exchange a Sign in with Apple credential for a HighFive session" } },
      [identityRefreshPath]: { post: { summary: "Refresh an authenticated HighFive identity session" } },
      [identitySignOutPath]: { post: { summary: "Sign out and revoke the current HighFive identity session" } },
      [identityDataExportPath]: { get: { summary: "Export sanitized local account, session, and audit data" } },
      [identityDeleteRequestPath]: { post: { summary: "Request account deletion and revoke local sessions" } },
      [identityAuditPath]: { get: { summary: "Fetch sanitized identity audit records" } },
      [securityRateLimitProbePath]: { get: { summary: "Exercise route-scoped rate limiting for security smoke tests" } },
      [openAPIPath]: { get: { summary: "Fetch OpenAPI document" } }
    }
  };
}
