import {
  catalogPath,
  catalogDeltaPath,
  catalogSyncPath,
  collectionDetailPath,
  contentDetailPath,
  analyticsDashboardPath,
  analyticsEventsPath,
  adminReviewAuditPath,
  adminReviewDetailPath,
  adminReviewQueuePath,
  creatorDraftDetailPath,
  creatorDraftsPath,
  creatorDraftSyncQueuePath,
  creatorDetailPath,
  creatorProcessingJobDetailPath,
  creatorProcessingJobsPath,
  creatorUploadAssetsPath,
  creatorUploadDetailPath,
  creatorUploadSessionsPath,
  discoveryQueryPath,
  aiDiscoveryHomePath,
  aiDiscoveryMoodPath,
  aiDiscoverySearchPath,
  socialWatchFriendsPath,
  socialWatchInviteDetailPath,
  socialWatchPartiesPath,
  socialWatchPartyDetailPath,
  socialWatchSharedLibraryPath,
  socialWatchSummaryPath,
  creatorEconomyDashboardPath,
  creatorEconomyMembershipsPath,
  creatorEconomyPaidCollectionsPath,
  creatorEconomyPaidPremieresPath,
  creatorEconomyPayoutsPath,
  creatorEconomyRevenueSharesPath,
  creatorEconomyTipsPath,
  creatorAssistantMetadataPath,
  creatorAssistantPosterPath,
  creatorAssistantPublishingPath,
  creatorAssistantRightsPath,
  creatorAssistantSEOPath,
  creatorAssistantSummaryPath,
  creatorAssistantTrailerPath,
  studioCollaborationCompaniesPath,
  studioCollaborationProjectDetailPath,
  studioCollaborationProjectsPath,
  studioCollaborationSummaryPath,
  studioCollaborationWorkspacesPath,
  livePremiereEventDetailPath,
  livePremiereEventsPath,
  livePremiereSummaryPath,
  deviceExpansionAirPlaySessionsPath,
  deviceExpansionHandoffPath,
  deviceExpansionProfileDetailPath,
  deviceExpansionProfilesPath,
  deviceExpansionSummaryPath,
  enterpriseStudioAnalyticsPath,
  enterpriseStudioBulkPublishingPath,
  enterpriseStudioDistributionReportPath,
  enterpriseStudioRightsReportPath,
  enterpriseStudioSummaryPath,
  performanceScaleLargeCatalogPath,
  performanceScaleSearchIndexPath,
  performanceScaleSummaryPath,
  performanceScaleSyncTuningPath,
  performanceScaleWarmCachePath,
  cinemaTwoAccessibilityPath,
  cinemaTwoMarketingAssetsPath,
  cinemaTwoPolishAuditPath,
  cinemaTwoReleaseChecklistPath,
  cinemaTwoSummaryPath,
  v3PersonalizationAdaptiveDiscoveryPath,
  v3PersonalizationHomePath,
  v3PersonalizationMoodEnginePath,
  v3PersonalizationTasteGraphPath,
  v3SearchCreatorSimilarityPath,
  v3SearchQueryPath,
  v3SearchRecommendationPath,
  v3SearchSemanticPath,
  v3SearchVisualSimilarityPath,
  v3SearchVoicePath,
  v3CreatorCopilotAudiencePath,
  v3CreatorCopilotGenerationPlanPath,
  v3CreatorCopilotPublishingPath,
  v3CreatorCopilotReleaseTimingPath,
  v3CreatorCopilotSummaryPath,
  v3CreatorCRMContractsPath,
  v3CreatorCRMDeliverablesPath,
  v3CreatorCRMInboxPath,
  v3CreatorCRMMilestonesPath,
  v3CreatorCRMSummaryPath,
  v3CreatorCRMTasksPath,
  v3CreatorCRMTeamsPath,
  v3ProductionAssetsPath,
  v3ProductionBudgetsPath,
  v3ProductionCrewPath,
  v3ProductionFilmsPath,
  v3ProductionProjectsPath,
  v3ProductionSchedulePath,
  v3ProductionSeriesPath,
  v3ProductionSummaryPath,
  identityDataExportPath,
  identityDeleteRequestPath,
  identityAppleExchangePath,
  identityAuditPath,
  identityDevSignInPath,
  identityMePath,
  identityRefreshPath,
  identitySignOutPath,
  notificationDeliveryAuditPath,
  notificationDevicesPath,
  notificationInboxPath,
  notificationPreferencesPath,
  notificationTestPushPath,
  monetizationAuditPath,
  monetizationEntitlementsPath,
  monetizationProductsPath,
  monetizationRestorePath,
  monetizationRevokePath,
  monetizationTransactionsPath,
  openAPIPath,
  platformOperationsAuditPath,
  platformOperationsModerationDetailPath,
  platformOperationsModerationFlagsPath,
  platformOperationsModerationPath,
  platformOperationsRightsDetailPath,
  platformOperationsRightsPath,
  platformOperationsSummaryPath,
  betaAuditPath,
  betaCrashDetailPath,
  betaCrashReportsPath,
  betaEnrollPath,
  betaFeedbackDetailPath,
  betaFeedbackPath,
  betaProgramPath,
  betaStabilityPath,
  publicReleaseAuditPath,
  publicReleaseCreatorOnboardingPath,
  publicReleaseCutoverPath,
  publicReleaseHotfixDetailPath,
  publicReleaseHotfixPath,
  publicReleaseMonitorPath,
  publicReleaseSubmitPath,
  publicReleaseSummaryPath,
  playbackDescriptorPath,
  playbackHLSPath,
  readinessPath,
  securityRateLimitProbePath,
  viewerLibraryOfflinePath,
  viewerLibraryPath,
  viewerLibraryProgressPath,
  viewerLibrarySavePath
} from "../contracts.js";

export function openAPISpec(): Record<string, unknown> {
  return {
    openapi: "3.1.0",
    info: {
      title: "HighFive Cinema Production Backend Foundation",
      version: "0.29.0",
      description: "Read-only local catalog foundation for P29A. Authentication, uploads, payments, and media processing are out of scope."
    },
    paths: {
      "/health": { get: { summary: "Health check" } },
      [readinessPath]: { get: { summary: "Readiness check" } },
      [catalogPath]: { get: { summary: "Fetch read-only catalog" } },
      [catalogSyncPath]: { get: { summary: "Fetch full catalog sync snapshot" } },
      [catalogDeltaPath]: { get: { summary: "Fetch catalog delta sync payload" } },
      [`${contentDetailPath}{id}`]: { get: { summary: "Fetch content detail" } },
      [`${creatorDetailPath}{id}`]: { get: { summary: "Fetch creator detail" } },
      [`${collectionDetailPath}{id}`]: { get: { summary: "Fetch collection detail" } },
      [creatorDraftsPath]: {
        get: { summary: "List authenticated creator drafts" },
        post: { summary: "Create authenticated creator draft" }
      },
      [`${creatorDraftDetailPath}{id}`]: {
        get: { summary: "Fetch authenticated creator draft" },
        patch: { summary: "Update authenticated creator draft with optimistic concurrency" }
      },
      [`${creatorDraftDetailPath}{id}/archive`]: { post: { summary: "Archive authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/restore`]: { post: { summary: "Restore authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/submit`]: { post: { summary: "Submit creator project for admin review" } },
      [`${creatorDraftDetailPath}{id}/withdraw`]: { post: { summary: "Withdraw creator project from admin review" } },
      [`${creatorDraftDetailPath}{id}/revisions`]: { get: { summary: "Fetch creator draft revision history" } },
      [creatorDraftSyncQueuePath]: { get: { summary: "Fetch creator draft sync queue audit records" } },
      [adminReviewQueuePath]: { get: { summary: "Fetch admin publishing review queue" } },
      [`${adminReviewDetailPath}{id}/request-revision`]: { post: { summary: "Request creator revisions for a reviewed project" } },
      [`${adminReviewDetailPath}{id}/approve`]: { post: { summary: "Approve reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/reject`]: { post: { summary: "Reject reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/schedule`]: { post: { summary: "Schedule approved creator project" } },
      [`${adminReviewDetailPath}{id}/publish`]: { post: { summary: "Publish approved creator project into public catalog" } },
      [`${adminReviewDetailPath}{id}/unpublish`]: { post: { summary: "Remove published creator project from public catalog" } },
      [`${adminReviewDetailPath}{id}/archive`]: { post: { summary: "Archive reviewed creator project" } },
      [adminReviewAuditPath]: { get: { summary: "Fetch admin publishing audit trail" } },
      [creatorUploadSessionsPath]: { post: { summary: "Create short-lived creator upload session" } },
      [`${creatorUploadDetailPath}{id}/blob`]: { put: { summary: "Upload verified asset bytes into local object storage" } },
      [`${creatorUploadDetailPath}{id}/cancel`]: { post: { summary: "Cancel creator upload session and cleanup local staging object" } },
      [creatorUploadAssetsPath]: { get: { summary: "List uploaded creator asset records" } },
      [creatorProcessingJobsPath]: {
        get: { summary: "List creator media processing jobs" },
        post: { summary: "Create local media processing job for uploaded asset" }
      },
      [`${creatorProcessingJobDetailPath}{id}/retry`]: { post: { summary: "Retry a failed or completed media processing job idempotently" } },
      [playbackDescriptorPath]: { post: { summary: "Resolve a short-lived playback descriptor for entitled content" } },
      [`${playbackHLSPath}{id}/master.m3u8`]: { get: { summary: "Fetch signed local HLS master manifest for a processed asset" } },
      [viewerLibraryPath]: { get: { summary: "Fetch authenticated viewer library, progress, and offline state" } },
      [viewerLibrarySavePath]: { post: { summary: "Save or remove authenticated viewer library title state" } },
      [viewerLibraryProgressPath]: { post: { summary: "Persist authenticated viewer playback progress" } },
      [viewerLibraryOfflinePath]: { post: { summary: "Persist authenticated viewer offline download state" } },
      [discoveryQueryPath]: { get: { summary: "Search, filter, paginate, and recommend catalog content" } },
      [aiDiscoveryHomePath]: { get: { summary: "Fetch personalized V2 home recommendations, taste profile, mood rails, and continue-watching intelligence" } },
      [aiDiscoverySearchPath]: { get: { summary: "Fetch V2 taste-aware ranked search results with matched-field explanations" } },
      [aiDiscoveryMoodPath]: { get: { summary: "Fetch V2 mood-based discovery recommendations" } },
      [socialWatchSummaryPath]: { get: { summary: "Fetch authenticated Social Watch parties, invites, comments, reactions, friends, and voice-room state" } },
      [socialWatchFriendsPath]: { post: { summary: "Create or fetch an authenticated friend relationship for Social Watch" } },
      [socialWatchSharedLibraryPath]: { post: { summary: "Share an authenticated local library selection with another user" } },
      [socialWatchPartiesPath]: { post: { summary: "Create an authenticated watch party for catalog content" } },
      [`${socialWatchPartyDetailPath}{id}/invite`]: { post: { summary: "Invite a user to an existing watch party" } },
      [`${socialWatchPartyDetailPath}{id}/playback`]: { post: { summary: "Synchronize watch-party playback position and state" } },
      [`${socialWatchPartyDetailPath}{id}/reactions`]: { post: { summary: "Record a watch-party reaction at a playback position" } },
      [`${socialWatchPartyDetailPath}{id}/comments`]: { post: { summary: "Record a watch-party comment at a playback position" } },
      [`${socialWatchPartyDetailPath}{id}/voice-room`]: { post: { summary: "Update local voice-room state for a watch party" } },
      [`${socialWatchInviteDetailPath}{id}/respond`]: { post: { summary: "Accept or decline an authenticated watch-party invite" } },
      [creatorEconomyDashboardPath]: { get: { summary: "Fetch creator economy dashboard with revenue, memberships, packages, and payout preview" } },
      [creatorEconomyPayoutsPath]: {
        get: { summary: "Fetch creator payout previews and available creator net revenue" },
        post: { summary: "Queue a creator payout preview without external transfer" }
      },
      [creatorEconomyRevenueSharesPath]: { post: { summary: "Update creator revenue share rules for owned content" } },
      [creatorEconomyTipsPath]: { post: { summary: "Record a viewer tip into the creator economy ledger" } },
      [creatorEconomyMembershipsPath]: { post: { summary: "Activate a viewer creator-membership ledger record" } },
      [creatorEconomyPaidCollectionsPath]: { post: { summary: "Create a creator paid collection package" } },
      [creatorEconomyPaidPremieresPath]: { post: { summary: "Create a creator paid premiere package" } },
      [creatorAssistantSummaryPath]: {
        get: { summary: "Fetch local creator assistant suggestions for the authenticated workspace" },
        post: { summary: "Fetch local creator assistant suggestions for an explicit project context" }
      },
      [creatorAssistantMetadataPath]: { post: { summary: "Generate local metadata suggestions for a creator project" } },
      [creatorAssistantPosterPath]: { post: { summary: "Generate local poster direction suggestions for a creator project" } },
      [creatorAssistantTrailerPath]: { post: { summary: "Generate local trailer structure suggestions for a creator project" } },
      [creatorAssistantPublishingPath]: { post: { summary: "Generate local publishing readiness suggestions for a creator project" } },
      [creatorAssistantSEOPath]: { post: { summary: "Generate local search and SEO suggestions for a creator project" } },
      [creatorAssistantRightsPath]: { post: { summary: "Generate local rights readiness suggestions for a creator project" } },
      [studioCollaborationSummaryPath]: { get: { summary: "Fetch studio collaboration companies, workspaces, shared projects, approvals, and activity" } },
      [studioCollaborationCompaniesPath]: { post: { summary: "Create a production company for the authenticated creator" } },
      [studioCollaborationWorkspacesPath]: { post: { summary: "Create a studio workspace under a production company" } },
      [studioCollaborationProjectsPath]: { post: { summary: "Share a creator project into a studio workspace" } },
      [`${studioCollaborationProjectDetailPath}{id}/collaborators`]: { post: { summary: "Add or update a project collaborator with role permissions" } },
      [`${studioCollaborationProjectDetailPath}{id}/edits`]: { post: { summary: "Record a multi-user edit on a shared project" } },
      [`${studioCollaborationProjectDetailPath}{id}/approvals`]: { post: { summary: "Request studio approval for a shared project" } },
      [`${studioCollaborationProjectDetailPath}{id}/approvals/{approvalID}/decision`]: { post: { summary: "Approve or request revisions for a studio approval" } },
      [livePremiereSummaryPath]: { get: { summary: "Fetch live premiere events, rooms, countdowns, chat, Q&A, intros, and replay state" } },
      [livePremiereEventsPath]: { post: { summary: "Create a live premiere event for a creator title" } },
      [`${livePremiereEventDetailPath}{id}/room`]: { post: { summary: "Update or join a live premiere room" } },
      [`${livePremiereEventDetailPath}{id}/countdown`]: { post: { summary: "Update live premiere countdown state" } },
      [`${livePremiereEventDetailPath}{id}/chat`]: { post: { summary: "Record a live premiere room chat message" } },
      [`${livePremiereEventDetailPath}{id}/intro`]: { post: { summary: "Record a creator introduction for a live premiere" } },
      [`${livePremiereEventDetailPath}{id}/qa`]: { post: { summary: "Submit a live premiere Q&A question" } },
      [`${livePremiereEventDetailPath}{id}/qa/{questionID}/answer`]: { post: { summary: "Answer a live premiere Q&A question" } },
      [`${livePremiereEventDetailPath}{id}/replay`]: { post: { summary: "Publish a replay record for a live premiere" } },
      [deviceExpansionSummaryPath]: { get: { summary: "Fetch device expansion profiles, AirPlay planning records, and handoff records" } },
      [deviceExpansionProfilesPath]: { get: { summary: "Fetch all client device capability profiles" } },
      [`${deviceExpansionProfileDetailPath}{id}`]: { get: { summary: "Fetch one device capability profile and layout recommendations" } },
      [deviceExpansionAirPlaySessionsPath]: { post: { summary: "Create a local AirPlay session planning record" } },
      [deviceExpansionHandoffPath]: { post: { summary: "Create a local cross-device handoff record" } },
      [enterpriseStudioSummaryPath]: { get: { summary: "Fetch enterprise studio dashboard, analytics, rights, distribution, and bulk publishing state" } },
      [enterpriseStudioAnalyticsPath]: { get: { summary: "Fetch studio analytics and enterprise portfolio metrics" } },
      [enterpriseStudioBulkPublishingPath]: { post: { summary: "Create a bulk publishing validation batch" } },
      [enterpriseStudioRightsReportPath]: { get: { summary: "Fetch enterprise rights management report" } },
      [enterpriseStudioDistributionReportPath]: { get: { summary: "Fetch enterprise distribution reporting summary" } },
      [performanceScaleSummaryPath]: { get: { summary: "Fetch performance and scale diagnostics" } },
      [performanceScaleWarmCachePath]: { post: { summary: "Warm local catalog, search, collection, and series caches" } },
      [performanceScaleLargeCatalogPath]: { get: { summary: "Fetch a virtualized large-catalog page for pagination validation" } },
      [performanceScaleSearchIndexPath]: { get: { summary: "Fetch search index diagnostics and ranking-field coverage" } },
      [performanceScaleSyncTuningPath]: { post: { summary: "Record background sync and stale-while-revalidate tuning" } },
      [cinemaTwoSummaryPath]: { get: { summary: "Fetch HighFive Cinema 2.0 release-readiness summary" } },
      [cinemaTwoPolishAuditPath]: { get: { summary: "Fetch final UI polish and protected-boundary audit" } },
      [cinemaTwoAccessibilityPath]: { get: { summary: "Fetch accessibility readiness report" } },
      [cinemaTwoMarketingAssetsPath]: { get: { summary: "Fetch launch marketing asset manifest" } },
      [cinemaTwoReleaseChecklistPath]: { get: { summary: "Fetch HighFive Cinema 2.0 release checklist" } },
      [v3PersonalizationHomePath]: { get: { summary: "Fetch V3 personalized home with taste graph, mood engine, behavior learning, and dynamic collections" } },
      [v3PersonalizationTasteGraphPath]: { get: { summary: "Fetch V3 local taste graph and behavior-learning summary" } },
      [v3PersonalizationMoodEnginePath]: { get: { summary: "Fetch V3 mood engine with deterministic mood rails" } },
      [v3PersonalizationAdaptiveDiscoveryPath]: { get: { summary: "Fetch V3 adaptive discovery layout strategy and dynamic collections" } },
      [v3SearchQueryPath]: { get: { summary: "Run V3 natural-language search against local catalog and personalization signals" } },
      [v3SearchSemanticPath]: { get: { summary: "Run V3 semantic search with local concept expansion" } },
      [v3SearchVisualSimilarityPath]: { get: { summary: "Fetch V3 visual-similarity title matches from local metadata" } },
      [v3SearchCreatorSimilarityPath]: { get: { summary: "Fetch V3 creator-similarity matches from local catalog relationships" } },
      [v3SearchVoicePath]: { get: { summary: "Run V3 transcript-normalized voice search locally" } },
      [v3SearchRecommendationPath]: { get: { summary: "Run V3 recommendation search against personalization context" } },
      [v3CreatorCopilotSummaryPath]: {
        get: { summary: "Fetch V3 local creator copilot summary for the authenticated workspace" },
        post: { summary: "Fetch V3 local creator copilot summary for an explicit project context" }
      },
      [v3CreatorCopilotGenerationPlanPath]: { post: { summary: "Generate V3 local creator metadata, poster, and trailer plan" } },
      [v3CreatorCopilotAudiencePath]: { post: { summary: "Generate V3 local creator audience targeting suggestions" } },
      [v3CreatorCopilotReleaseTimingPath]: { post: { summary: "Generate V3 local creator release timing recommendations" } },
      [v3CreatorCopilotPublishingPath]: { post: { summary: "Generate V3 local creator publishing recommendations" } },
      [v3CreatorCRMSummaryPath]: { get: { summary: "Fetch V3 local creator CRM inbox, contracts, tasks, milestones, teams, and deliverables" } },
      [v3CreatorCRMInboxPath]: { post: { summary: "Create a local creator CRM inbox record" } },
      [v3CreatorCRMContractsPath]: { post: { summary: "Create a local creator CRM contract planning record" } },
      [v3CreatorCRMTasksPath]: { post: { summary: "Create a local creator CRM task record" } },
      [v3CreatorCRMMilestonesPath]: { post: { summary: "Create a local creator CRM milestone record" } },
      [v3CreatorCRMTeamsPath]: { post: { summary: "Create a local creator CRM team record" } },
      [v3CreatorCRMDeliverablesPath]: { post: { summary: "Create a local creator CRM deliverable record" } },
      [v3ProductionSummaryPath]: { get: { summary: "Fetch V3 local production management films, series, projects, schedules, budgets, crew, and assets" } },
      [v3ProductionFilmsPath]: { post: { summary: "Create a local production film record" } },
      [v3ProductionSeriesPath]: { post: { summary: "Create a local production series record" } },
      [v3ProductionProjectsPath]: { post: { summary: "Create a local production project record" } },
      [v3ProductionSchedulePath]: { post: { summary: "Create a local production schedule record" } },
      [v3ProductionBudgetsPath]: { post: { summary: "Create a local production budget record" } },
      [v3ProductionCrewPath]: { post: { summary: "Create a local production crew record" } },
      [v3ProductionAssetsPath]: { post: { summary: "Create a local production asset record" } },
      [analyticsEventsPath]: { post: { summary: "Ingest versioned analytics event batches with idempotency and privacy controls" } },
      [analyticsDashboardPath]: { get: { summary: "Fetch aggregate analytics for creator and platform dashboards" } },
      [notificationDevicesPath]: { post: { summary: "Register an APNs device token suffix for the authenticated user" } },
      [notificationPreferencesPath]: {
        get: { summary: "Fetch authenticated notification preferences" },
        patch: { summary: "Update authenticated notification preferences" }
      },
      [notificationInboxPath]: { get: { summary: "Fetch authenticated in-app notification inbox" } },
      [notificationTestPushPath]: { post: { summary: "Queue a development notification and delivery audit record" } },
      [notificationDeliveryAuditPath]: { get: { summary: "Fetch notification delivery audit records" } },
      [monetizationProductsPath]: { get: { summary: "Fetch StoreKit 2 product catalog and entitlement scopes" } },
      [monetizationEntitlementsPath]: { get: { summary: "Fetch authenticated backend entitlement records" } },
      [monetizationTransactionsPath]: { post: { summary: "Record verified StoreKit 2 transaction state" } },
      [monetizationRestorePath]: { post: { summary: "Restore authenticated active entitlement records" } },
      [monetizationRevokePath]: { post: { summary: "Revoke authenticated product entitlement" } },
      [monetizationAuditPath]: { get: { summary: "Fetch authenticated monetization audit events" } },
      [platformOperationsSummaryPath]: { get: { summary: "Fetch admin rights, moderation, availability, and health summary" } },
      [platformOperationsRightsPath]: { get: { summary: "Fetch admin rights windows and territory availability" } },
      [`${platformOperationsRightsDetailPath}{id}/expire`]: { post: { summary: "Expire rights window and remove catalog availability" } },
      [`${platformOperationsRightsDetailPath}{id}/restore`]: { post: { summary: "Restore rights window and catalog availability" } },
      [platformOperationsModerationPath]: { get: { summary: "Fetch admin moderation queue" } },
      [platformOperationsModerationFlagsPath]: { post: { summary: "Flag content for moderation review" } },
      [`${platformOperationsModerationDetailPath}{id}/clear`]: { post: { summary: "Clear moderation case" } },
      [`${platformOperationsModerationDetailPath}{id}/needs-revision`]: { post: { summary: "Request moderation revision" } },
      [`${platformOperationsModerationDetailPath}{id}/takedown`]: { post: { summary: "Apply moderation takedown and remove catalog availability" } },
      [`${platformOperationsModerationDetailPath}{id}/restore`]: { post: { summary: "Restore content from moderation takedown" } },
      [platformOperationsAuditPath]: { get: { summary: "Fetch platform operations audit trail" } },
      [betaProgramPath]: { get: { summary: "Fetch admin beta program status, cohorts, stability, and open issues" } },
      [betaEnrollPath]: { post: { summary: "Enroll an authenticated account into an allowed beta cohort" } },
      [betaFeedbackPath]: { post: { summary: "Submit beta feedback for an enrolled tester" } },
      [`${betaFeedbackDetailPath}{id}/resolve`]: { post: { summary: "Resolve or triage beta feedback as an admin" } },
      [betaCrashReportsPath]: { post: { summary: "Submit a beta crash report for an enrolled tester" } },
      [`${betaCrashDetailPath}{id}/resolve`]: { post: { summary: "Resolve a beta crash report as an admin" } },
      [betaStabilityPath]: { get: { summary: "Fetch beta stability summary for launch readiness" } },
      [betaAuditPath]: { get: { summary: "Fetch beta operations audit trail" } },
      [publicReleaseSummaryPath]: { get: { summary: "Fetch public release state, monitoring, launch analytics, hotfixes, and onboarding" } },
      [publicReleaseSubmitPath]: { post: { summary: "Record public release submission state and manual external submission confirmation" } },
      [publicReleaseCutoverPath]: { post: { summary: "Record public release cutover after manual public release confirmation" } },
      [publicReleaseMonitorPath]: { get: { summary: "Fetch public release monitoring and launch analytics snapshot" } },
      [publicReleaseHotfixPath]: { post: { summary: "Open a public release hotfix tracking record" } },
      [`${publicReleaseHotfixDetailPath}{id}/update`]: { post: { summary: "Update public release hotfix state" } },
      [publicReleaseCreatorOnboardingPath]: { post: { summary: "Record launch creator onboarding state" } },
      [publicReleaseAuditPath]: { get: { summary: "Fetch public release audit trail" } },
      [identityMePath]: { get: { summary: "Fetch authenticated session and permission summary" } },
      [identityDevSignInPath]: { post: { summary: "Create a simulator development identity session" } },
      [identityAppleExchangePath]: { post: { summary: "Exchange a Sign in with Apple credential for a HighFive session" } },
      [identityRefreshPath]: { post: { summary: "Refresh an authenticated HighFive identity session" } },
      [identitySignOutPath]: { post: { summary: "Sign out and revoke the current HighFive identity session" } },
      [identityDataExportPath]: { get: { summary: "Export sanitized local account, session, and audit data" } },
      [identityDeleteRequestPath]: { post: { summary: "Request account deletion and revoke local sessions" } },
      [identityAuditPath]: { get: { summary: "Fetch sanitized identity audit records" } },
      [securityRateLimitProbePath]: { get: { summary: "Exercise route-scoped rate limiting for security smoke tests" } },
      [openAPIPath]: { get: { summary: "Fetch OpenAPI document" } }
    }
  };
}
