import {
  catalogPath,
  catalogDeltaPath,
  catalogSyncPath,
  collectionDetailPath,
  contentDetailPath,
  analyticsDashboardPath,
  analyticsEventsPath,
  adminReviewAuditPath,
  adminReviewDetailPath,
  adminReviewQueuePath,
  creatorDraftDetailPath,
  creatorDraftsPath,
  creatorDraftSyncQueuePath,
  creatorDetailPath,
  creatorProcessingJobDetailPath,
  creatorProcessingJobsPath,
  creatorUploadAssetsPath,
  creatorUploadDetailPath,
  creatorUploadSessionsPath,
  discoveryQueryPath,
  notificationDeliveryAuditPath,
  notificationDevicesPath,
  notificationInboxPath,
  notificationPreferencesPath,
  notificationTestPushPath,
  monetizationAuditPath,
  monetizationEntitlementsPath,
  monetizationProductsPath,
  monetizationRestorePath,
  monetizationRevokePath,
  monetizationTransactionsPath,
  openAPIPath,
  playbackDescriptorPath,
  playbackHLSPath,
  readinessPath,
  viewerLibraryOfflinePath,
  viewerLibraryPath,
  viewerLibraryProgressPath,
  viewerLibrarySavePath
} from "../contracts.js";

export function openAPISpec(): Record<string, unknown> {
  return {
    openapi: "3.1.0",
    info: {
      title: "HighFive Cinema Production Backend Foundation",
      version: "0.29.0",
      description: "Read-only local catalog foundation for P29A. Authentication, uploads, payments, and media processing are out of scope."
    },
    paths: {
      "/health": { get: { summary: "Health check" } },
      [readinessPath]: { get: { summary: "Readiness check" } },
      [catalogPath]: { get: { summary: "Fetch read-only catalog" } },
      [catalogSyncPath]: { get: { summary: "Fetch full catalog sync snapshot" } },
      [catalogDeltaPath]: { get: { summary: "Fetch catalog delta sync payload" } },
      [`${contentDetailPath}{id}`]: { get: { summary: "Fetch content detail" } },
      [`${creatorDetailPath}{id}`]: { get: { summary: "Fetch creator detail" } },
      [`${collectionDetailPath}{id}`]: { get: { summary: "Fetch collection detail" } },
      [creatorDraftsPath]: {
        get: { summary: "List authenticated creator drafts" },
        post: { summary: "Create authenticated creator draft" }
      },
      [`${creatorDraftDetailPath}{id}`]: {
        get: { summary: "Fetch authenticated creator draft" },
        patch: { summary: "Update authenticated creator draft with optimistic concurrency" }
      },
      [`${creatorDraftDetailPath}{id}/archive`]: { post: { summary: "Archive authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/restore`]: { post: { summary: "Restore authenticated creator draft" } },
      [`${creatorDraftDetailPath}{id}/submit`]: { post: { summary: "Submit creator project for admin review" } },
      [`${creatorDraftDetailPath}{id}/withdraw`]: { post: { summary: "Withdraw creator project from admin review" } },
      [`${creatorDraftDetailPath}{id}/revisions`]: { get: { summary: "Fetch creator draft revision history" } },
      [creatorDraftSyncQueuePath]: { get: { summary: "Fetch creator draft sync queue audit records" } },
      [adminReviewQueuePath]: { get: { summary: "Fetch admin publishing review queue" } },
      [`${adminReviewDetailPath}{id}/request-revision`]: { post: { summary: "Request creator revisions for a reviewed project" } },
      [`${adminReviewDetailPath}{id}/approve`]: { post: { summary: "Approve reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/reject`]: { post: { summary: "Reject reviewed creator project" } },
      [`${adminReviewDetailPath}{id}/schedule`]: { post: { summary: "Schedule approved creator project" } },
      [`${adminReviewDetailPath}{id}/publish`]: { post: { summary: "Publish approved creator project into public catalog" } },
      [`${adminReviewDetailPath}{id}/unpublish`]: { post: { summary: "Remove published creator project from public catalog" } },
      [`${adminReviewDetailPath}{id}/archive`]: { post: { summary: "Archive reviewed creator project" } },
      [adminReviewAuditPath]: { get: { summary: "Fetch admin publishing audit trail" } },
      [creatorUploadSessionsPath]: { post: { summary: "Create short-lived creator upload session" } },
      [`${creatorUploadDetailPath}{id}/blob`]: { put: { summary: "Upload verified asset bytes into local object storage" } },
      [`${creatorUploadDetailPath}{id}/cancel`]: { post: { summary: "Cancel creator upload session and cleanup local staging object" } },
      [creatorUploadAssetsPath]: { get: { summary: "List uploaded creator asset records" } },
      [creatorProcessingJobsPath]: {
        get: { summary: "List creator media processing jobs" },
        post: { summary: "Create local media processing job for uploaded asset" }
      },
      [`${creatorProcessingJobDetailPath}{id}/retry`]: { post: { summary: "Retry a failed or completed media processing job idempotently" } },
      [playbackDescriptorPath]: { post: { summary: "Resolve a short-lived playback descriptor for entitled content" } },
      [`${playbackHLSPath}{id}/master.m3u8`]: { get: { summary: "Fetch signed local HLS master manifest for a processed asset" } },
      [viewerLibraryPath]: { get: { summary: "Fetch authenticated viewer library, progress, and offline state" } },
      [viewerLibrarySavePath]: { post: { summary: "Save or remove authenticated viewer library title state" } },
      [viewerLibraryProgressPath]: { post: { summary: "Persist authenticated viewer playback progress" } },
      [viewerLibraryOfflinePath]: { post: { summary: "Persist authenticated viewer offline download state" } },
      [discoveryQueryPath]: { get: { summary: "Search, filter, paginate, and recommend catalog content" } },
      [analyticsEventsPath]: { post: { summary: "Ingest versioned analytics event batches with idempotency and privacy controls" } },
      [analyticsDashboardPath]: { get: { summary: "Fetch aggregate analytics for creator and platform dashboards" } },
      [notificationDevicesPath]: { post: { summary: "Register an APNs device token suffix for the authenticated user" } },
      [notificationPreferencesPath]: {
        get: { summary: "Fetch authenticated notification preferences" },
        patch: { summary: "Update authenticated notification preferences" }
      },
      [notificationInboxPath]: { get: { summary: "Fetch authenticated in-app notification inbox" } },
      [notificationTestPushPath]: { post: { summary: "Queue a development notification and delivery audit record" } },
      [notificationDeliveryAuditPath]: { get: { summary: "Fetch notification delivery audit records" } },
      [monetizationProductsPath]: { get: { summary: "Fetch StoreKit 2 product catalog and entitlement scopes" } },
      [monetizationEntitlementsPath]: { get: { summary: "Fetch authenticated backend entitlement records" } },
      [monetizationTransactionsPath]: { post: { summary: "Record verified StoreKit 2 transaction state" } },
      [monetizationRestorePath]: { post: { summary: "Restore authenticated active entitlement records" } },
      [monetizationRevokePath]: { post: { summary: "Revoke authenticated product entitlement" } },
      [monetizationAuditPath]: { get: { summary: "Fetch authenticated monetization audit events" } },
      [openAPIPath]: { get: { summary: "Fetch OpenAPI document" } }
    }
  };
}
